- name: Install patch library to build nokogiri gem
  apt: "pkg=patch state=installed"

- name: Install python software properties (needed to add the nodejs ppa)
  apt: "pkg=python-software-properties state=installed"

- name: Add nodejs ppa
  apt_repository: repo='ppa:chris-lea/node.js' state=present

- name: update apt packages
  apt: update_cache=true

- name: Install nodejs (needed because of execjs)
  apt: "pkg=nodejs state=installed"

- name: Install "karma" package
  npm: name=karma global=true state=latest

- name: Install "karma-phantomjs-launcher" package
  npm: name=karma-phantomjs-launcher global=true state=latest

- name: Set PHANTOMJS_BIN environment variable
  shell: "echo $PHANTOMJS_BIN"
  environment:
    PHANTOMJS_BIN: /vagrant/transervicos/node_modules/phantomjs-prebuilt/bin/phantomjs

- name: Install "grunt-cli" package
  npm: name=grunt-cli global=true state=latest

- name: Install "grunt-karma" package
  npm: name=grunt-karma global=true state=latest

- name: Install libfontconfig (needed because of phantomjs)
  apt: "pkg=libfontconfig state=installed"

- name: install ruby dependencies
  command: bash -lc 'bundle install' chdir={{ base_path }}
  sudo_user: vagrant
